
#Field light artillery

#==============================
[fieldLight]
#healthpoints of the artillery
health = 20
#The cooldown time to wait until the artillery can fire again, if reloading is disabled
#if cooldown is disabled the firing speed is still gated by the time required to play out
#the current animation and current shot being fired.
cooldown = 3000


#==============================
#Field Heavy artillery
[fieldHeavy]
health = 80
cooldown = 5000

#==============================
#Heavy flak

[heavyFlak]
health = 100
cooldown = 5000

#==============================
#Light flak
[lightFlak]
health = 15
cooldown = 500

#ammo drum size of the light flak before needing reload
#set to -1 to allow arbitrary length belt feeding
magSize = 40

#The percent chance for any one shot to jam the gun. float value, 0 to 1.
jamPercent = 0

#the amount of heat which should be incurred per shot.
#float value, [0-100], where 100 is max heat. If the gun is fired beyond max heat it will take damage.
overheat = 1


#the rate at which the gun cools down. [0-100]
heatDissipationRate = 1

#The amount of time in ticks after shooting to wait before the gun starts cooling down
inactiveHeatTicks = 2000
#==============================
#Heavy machine gun

[heavyMachineGun]
health = 15

#ammo drum size of the machine gun before needing reload.
#set to -1 to allow arbitrary length belt feeding
magSize = -1

#The percent chance for any one shot to jam the gun. float value, [0 - 1]
jamPercent = 0.01

#the amount of heat which should be incurred per shot.
#float value, [0-100], where 100 is max heat. If the gun is fired beyond max heat it will take damage.
overheat = 0.8

#the rate at which the gun cools down. [0-100]
heatDissipationRate = 1

#The amount of time in ticks after shooting to wait before the gun starts cooling down
inactiveHeatTicks = 2000


#==============================
#Missile launcher
[missileLauncher]
health = 35
cooldown = 10000
missiles = 6

#==============================
#Railgun
[railGun]
health = 50

#The cooldown for the railgun works a bit differently.
#This is the time required until the next shot is fully charged
cooldown = 1000

#max range of the railgun
range = 500


# damage on a fully charged shot. Lower power shots will deal a percentage of this number.
maxdamage = 150
#==============================

[cram]
health = 30
cooldown = 500

#==============================
#General options

[general]
#Explosion power of the ammo (How big and how much damage the shell should do)
#Because of vanilla limitations with particles, explosion power above the recommended may result in
#custom explosions looking undersized

#recommended power: 4
heavyHighExplosive = 4
heavyFlak = 4
missile = 4
standard = 4
#light flak always explodes with an explosion power of 1
#same with CRAM

# If a shell hits the target directly, how much damage the target should receive.
# this damage is applied before explosion damage if the shell is explosive.
# missiles do no contact damage
heavyHighExplosiveDamage = 10
heavyFlakDamage = 10
standardDamage = 10

lightStandardDamage = 5
lightFlakDamage = 5
cramDamage = 10
railgunDamage = 150


#Whether the explosions from the artillery should be
#vanilla explosions which call Spigot/Bukkit/Paper API events using world.createExplosion(...)
#or a custom explosion which might not
useVanillaExplosions = false

#Whether artillery destroys blocks
#this does not apply to falling blocks
destructiveArtillery = true

#whether artillery need to reload
requireReloading = true

#difficulty to dodge missiles. Decimal value from [0-100]
missileDifficulty = 100

#whether flares should be enabled to help players survive barrages of missiles
enableFlares = true




